CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE users
(
    user_id   BIGINT NOT NULL,
    user_name VARCHAR(255),
    password  VARCHAR(255),
    role      VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE car_service
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(255),
    address VARCHAR(255),
    manager VARCHAR(255),
    CONSTRAINT pk_carservice PRIMARY KEY (id)
);

CREATE TABLE foreman
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    surname        VARCHAR(255),
    rating         INT                                     NOT NULL,
    specialization VARCHAR(255),
    city           VARCHAR(255),
    menu_id        BIGINT,
    CONSTRAINT pk_foreman PRIMARY KEY (id)
);

ALTER TABLE foreman
    ADD CONSTRAINT FK_FOREMAN_ON_MENU FOREIGN KEY (menu_id) REFERENCES car_service (id);